M48
; DRILL file {KiCad 9.0.7} date 2026-03-26T17:44:32-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-26T17:44:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X28.75Y-28.75
X28.75Y-121.25
X121.25Y-28.75
X121.25Y-121.25
M30
